version: '2'
services:
  elastic:
    ports:
        - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: MYPASSWORD
    networks:
        - elasticNetwork
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    networks:
        - elasticNetwork
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
        - elastic
    ports:
      - "5601:5601"

networks:
    elasticNetwork:
        driver: bridge